### ISSUE TITLE
Please upgrade rockspec at luarocks.org

### ISSUE THREAD

**Issue by hishamhm** [hleuwer/luagraph#1]
Users are not finding the latest version of LuaGRAPH due to the outdated rockspec at luarocks.org and the outdated website at LuaForge:

http://stackoverflow.com/questions/32812703/how-to-install-luagraph-using-luarocks/42661145#42661145

The current rockspec for the old release is broken because it looks for `graphviz/graph.h` which is no longer included with Graphviz.

Is the account https://luarocks.org/modules/hleuwer at luarocks.org yours? I can transfer ownership of https://luarocks.org/modules/luarocks/luagraph to your account so you can upload a new version (it is currently orphan, owned by the placeholder "luarocks" account).

**Comment by hleuwer** [comment]
> Am 08.03.2017 um 06:00 schrieb Hisham Muhammad <notifications@github.com>:
> 
> Users are not finding the latest version of LuaGRAPH due to the outdated rockspec at luarocks.org and the outdated website at LuaForge:
> 
> The current rockspec for the old release is broken because it looks for graphviz/graph.h which is no longer included with Graphviz.
> 
> Is the account https://luarocks.org/modules/hleuwer at luarocks.org yours? I can transfer ownership of https://luarocks.org/modules/luarocks/luagraph to your account so you can upload a new version (it is currently orphan, owned by the placeholder "luarocks" account).
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
I never personally created a rock spec for luagraph. This was done based on a clone of luagraph. I have updated luagraph two weeks ago to work with newest Graphviz version. Its now based on the newer cgraph library and works with Lua 5.1 to 5.3. 
Still runtime problems on Windows 10 (look at the README). 
See here:
https://github.com/hleuwer/luagraph

—Herbert

**Comment by hleuwer** [comment]
> Am 09.03.2017 um 18:53 schrieb Herbert Leuwer <herbert.leuwer@t-online.de>:
> 
> 
>> Am 08.03.2017 um 06:00 schrieb Hisham Muhammad <notifications@github.com>:
>> 
>> Users are not finding the latest version of LuaGRAPH due to the outdated rockspec at luarocks.org and the outdated website at LuaForge:
>> 
>> The current rockspec for the old release is broken because it looks for graphviz/graph.h which is no longer included with Graphviz.
>> 
>> Is the account https://luarocks.org/modules/hleuwer at luarocks.org yours? I can transfer ownership of https://luarocks.org/modules/luarocks/luagraph to your account so you can upload a new version (it is currently orphan, owned by the placeholder "luarocks" account).
>> 
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub, or mute the thread.
>> 
> I never personally created a rock spec for luagraph. This was done based on a clone of luagraph. I have updated luagraph two weeks ago to work with newest Graphviz version. Its now based on the newer cgraph library and works with Lua 5.1 to 5.3. 
> Still runtime problems on Windows 10 (look at the README). 
> See here:
> https://github.com/hleuwer/luagraph
> 
> —Herbert
Sorry, missed your last question. Yes you may transfer ownership to me. When I find time I will learn how to build rocks and update luagraph for luarocks.

Thanks for your notice.
—Herbert

**Comment by hishamhm** [comment]
Done! Ownership is now transferred:
http://luarocks.org/modules/hleuwer/luagraph

**Comment by hleuwer** [comment]
luagraph-2.0.0-1.rockspec and luagraph-2.0.0-1.src.rock now available - closing

**Comment by hleuwer** [comment]
luagraph-2.0.0-1.rockspec and luagraph-2.0.0-1.src.rock now available
