### ISSUE TITLE
Incompatible with Lua 5.3

### ISSUE THREAD

**Issue by xordspar0** [hleuwer/luagraph#2]
The `luaL_register` function is deprecated starting in Lua version 5.2 and removed in Lua version 5.3, so `require`ing graph from Lua 5.3 fails with the following message:

```
lua: error loading module 'graph.core' from file '/usr/local/lib/lua/5.3/graph/core.so':
Error relocating /usr/local/lib/lua/5.3/graph/core.so: luaL_register: symbol not found
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	/usr/local/share/lua/5.3/graph.lua:9: in main chunk
	[C]: in function 'require'
	scripts/myscript.lua:1: in main chunk
	[C]: in ?
```

**Comment by hleuwer** [comment]
Thanks for reporting this issue.
Fixed in version 2.0.1-1 of luagraph and in master branch
I also uploaded a new rock to luarocks
